FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Second FROM instruction starts a new build stage 
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80